NOAA-GFDL/SHiELD_physics

- FV3GFS/FV3GFS_io.F90
- GFS_layer/GFS_radiation_driver.F90
From the Vulcan team: undefined/unintialized values
> Vulcan: undefined/unintialized values

- simple_coupler/coupler_main.F90
Implementing changes that Joseph Mouallem has made.  Changes were tested by Joseph and Rusty.
This will fix warnings when writing coupler.res which should be only written by one PE.
> Remove coupler warnings

- GFS_layer/GFS_typedefs.F90
- atmos_drivers/coupled/atmos_model.F90
A change to FMS 2021.02 requires an update to the way input_nml_file is declared in GFS_typedef.
This change has been tested with both GNU 10.2.0 and Intel 18.0.6.288 and the SHiELD model.
This change will work with the currently released FMS 2021.01 and does not cause answer changes.
> FMS 2021.02 input_nml_file update

- FV3GFS/FV3GFS_io.F90
- atmos_drivers/solo/atmos_model.F90
- simple_coupler/coupler_main.F90
This pull request implements fms2io into the SHiELD_driver code. In a coming release of FMS, the modules mpp_io_mod and fms_io_mod are being deprecated and replaced by the new fms2_io_mod.   These changes go hand in hand with the changes to the dycore in [PR74](https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/74)
These changes have been tested with SHiELD and do not change answers. Using FMS [2021.02-beta2 tag](https://github.com/NOAA-GFDL/FMS/releases/tag/2021.02-beta2) and GFDL_atmos_cubed_sphere [laurenchilutti:fms2_io_implementation](https://github.com/laurenchilutti/GFDL_atmos_cubed_sphere/tree/fms2_io_implementation)
Tests run are:
C48 grid test with coarse grained restarts and intermediate restarts and with …
> FMS2 io updates

- GFS_layer/GFS_driver.F90
- GFS_layer/GFS_typedefs.F90
- gsmphys/gfdl_cld_mp.F90
This PR and PR https://github.com/NOAA-GFDL/atmos_drivers/pull/24 address the following comment from the review of PR https://github.com/NOAA-GFDL/SHiELD_physics/pull/22:
"The designed way to get this information to the physics from outside is to use the GFS_init_type. This type is populated with dycore and other external to the physics information within the atmos_model.F90::atmos_model_init function and it is passed to GFS_Initialize, where it is passed to the Model%init procedure."
**Checklist:**
> Add variables to GFS_init_type

- FV3GFS/FV3GFS_io.F90
This PR implements the changes suggested in #29.  
Fixes #29
This has been tested in CI in https://github.com/ai2cm/SHiELD-wrapper/pull/4 (see tests defined [here](https://github.com/ai2cm/SHiELD-wrapper/blob/3c5af7c7739359099fcbce707d32185ef8ecc2e8/wrapper/tests/test_diagnostics.py#L12-L47)).  The model compiles successfully and with updates to the wrapper we are able to successfully get values of the physics diagnostics during simulations.
**Checklist:**
> Make `Diag` data structure public in FV3GFS_io.F90

- FV3GFS/FV3GFS_io.F90
- GFS_layer/GFS_abstraction_layer.F90
- GFS_layer/GFS_driver.F90
- GFS_layer/GFS_physics_driver.F90
- GFS_layer/GFS_typedefs.F90
- IPD_layer/IPD_driver.F90
- IPD_layer/IPD_typedefs.F90
This PR adds hooks to enable overriding the surface radiative fluxes seen by the land and ocean models following https://github.com/ai2cm/fv3gfs-fortran/pull/158 in AI2's fork of FV3GFS.  [This document](https://paper.dropbox.com/doc/2021-03-12-design-of-the-fortran-hooks-for-overriding-the-surface-radiative-fluxes-seen-by-the-surface-schemes-o4oxKjCgRxbfjrXMrCj7c) contains a description of the thought process behind this code in FV3GFS, which has been used in several studies.  In short it:
- Adds fields to a new data structure (`IPD_Data%OverridesFromPythonWrapper`) that are meant to hold data for overriding the surface radiative fluxes (namely the downward longwave, downward shortwave, and net shortwave radiative components).
- Creates pointers in the physics driver for …
> Add hooks for overriding surface radiative fluxes seen by land and ocean models

- FV3GFS/FV3GFS_io.F90
This is somewhat of a followup to #30.  In doing some more work I realized that it would also be useful if `gfdl_diag_type`  and `Diag_diag_manager_controlled` were made public in `FV3GFS_io.F90` as well.  @lharris4 and @bensonr let me know if this seems OK to you.
I have tested a feature that depends on this in a Python wrapped version of SHiELD in https://github.com/ai2cm/SHiELD-wrapper/pull/18.
**Checklist:**
> Make `gfdl_diag_type` and `Diag_diag_manager_controlled` in `FV3GFS_io.F90` public

- FV3GFS/FV3GFS_io.F90
- gsmphys/sfcsub.F
- gsmphys/som_mlm.F90
**Description** 
This PR fixes a bug in reading in a climatological Q-flux prescribed from a file, and adds a couple diagnostics to allow for easier inspection of the instantaneous values of the Q-flux and mixed layer depth prescribed.
Note I have included another minor change to the slab ocean model code, which removes the `iostat` argument from the namelist read call.  If `iostat` is included in this call and namelist parameters are mistyped, then the simulation will continue without reading the rest of the variables in the `ocean_nml` namelist, leading to difficult to debug / unexpected behavior.  With `iostat` removed—[as is done elsewhere in the code](https://github.com/NOAA-GFDL/SHiELD_physics/blob/d44f50f2cf0fab2b7919df84da5a419c01d55164/GFS_layer/GFS_typedefs.F90#L2528)—the model …
> Fix prescribed Q-flux bug and improve user experience of SOM

- .github/workflows/Intel_Parallelworks_CI.yaml
- .github/workflows/daily_cleanup_parallelworks.yaml
Adding CI tests to this repo. This brings over a similar workflow as is done in the GFDL_atmos_cubed_sphere repository. Will build solo model (nh, sw, and hydro) and then run the 35 tests in RTS/CI.
Tested by the successful checks on this PR
**Checklist:**
> Add CI to repo

- FV3GFS/FV3GFS_io.F90
In the most recent updates from PRs #35 and #36, a new subroutine is declared `compute_surface_type_fraction`
When I try to compile SHiELD 32bit, I get a type mismatch error at line 7255:
https://github.com/NOAA-GFDL/SHiELD_physics/blob/23a9ec02086577aa621b26331478199c3cb40552/FV3GFS/FV3GFS_io.F90#L7255
related to `var2d`
`var2d` is of `real(kind=kind_phys)`.  I believe that the type of the matching argument in `compute_surface_type_fraction` should also be the same.
tested with a build on Gaea.  Currently testing with regression tests.
**Checklist:**
> Fix type of input argument in compute_surface_type_fraction

- .github/workflows/Intel_Parallelworks_CI.yaml
- .github/workflows/daily_cleanup_parallelworks.yaml
Changes to the CI files.  Specifically mirroring improvements made to the GFDL_atmos_cubed_sphere CI.  Moving this CI to a new Parallelworks cloud cluster.  Reorganizing the file structure on Parallelworks.  Adding conditions so that the CI does not run in personal forks.
This will be tested by this PR.
**Checklist:**
> Updates for CI

- GFS_layer/GFS_physics_driver.F90
- GFS_layer/GFS_typedefs.F90
- gsmphys/module_sf_noahmp_glacier.f90
- gsmphys/module_sf_noahmplsm.f90
- gsmphys/radiation_surface.f
- gsmphys/sfc_noahmp_drv.f
This PR cherry-picks several commits from the internal version of the SHiELD physics to the public version.  They are from two MRs which @kaiyuan-cheng and I collaborated on in the internal version of SHiELD (internal GitLab access is required to follow some of the links).
cc: @lharris4
Question: do we have a policy for including the license(s) of code we bring in from these external repositories ([NCAR/noahmp](https://github.com/NCAR/noahmp) and [NCAR/ccpp-physics](https://github.com/NCAR/ccpp-physics))?
> Fixed a bug where albedo over the ocean is computed incorrectly when ialb = 2.
> 
> In the original code, the ocean fraction is always zero; therefore, the albedo over the ocean is miscalculated. In the fix, the ocean fraction is calculated following the logic used in …
> Port recent Noah-MP upgrades / fixes to public version of SHiELD

- FV3GFS/FV3GFS_io.F90
- GFS_layer/GFS_radiation_driver.F90
- GFS_layer/GFS_typedefs.F90
This PR adds a diagnostic for the global mean volume mixing ratio of CO2.  It does so following the conventions / approximations in `radlw_main.f`: https://github.com/NOAA-GFDL/SHiELD_physics/blob/5e5e100c068d55b8247dcb428f9df36fb31bdf35/gsmphys/radlw_main.f#L765-L806
It assumes the moles of CO2 per area can be computed by scaling the prescribed volume mixing ratio of CO2 by the moles of dry air per area.  A global mean volume mixing ratio then can be computed by dividing the total moles of CO2 globally the by the total moles of dry air globally.
This has been tested in a three-month C24 simulation outputting the instantaneous global mean CO2 concentration every 6 hours.  The plot of the time series can be found below. 
The simulation uses …
> Add global mean CO2 diagnostic

- FV3GFS/FV3GFS_io.F90
- GFS_layer/GFS_physics_driver.F90
This PR adds an instantaneous snow cover fraction diagnostic to SHiELD.  When plotting this field, one somewhat odd aspect that stood out is that the snow cover is non-zero over some ocean grid cells.  For the test run I did this was most noticeable in the North Pole tile.  This is illustrated in the figure below, which plots snapshots of the snow cover, snow depth, and snow water equivalent depth for the North Pole tile masked to only ocean grid cells.  The snow cover is non-zero at some points, but the snow depth and snow water equivalent depth are zero everywhere (which is more in line with what we would expect).
This has been tested by running a short C24 resolution simulation and plotting the result for the diagnostic and comparing it …
> Add instantaneous snow fraction diagnostic

- FV3GFS/FV3GFS_io.F90
- GFS_layer/GFS_physics_driver.F90
- GFS_layer/GFS_typedefs.F90
- gsmphys/gcycle.F90
- gsmphys/noahmp_tables.f90
- gsmphys/sfc_noahmp_drv.f
- gsmphys/sfcsub.F
Previously in SHiELD the soil color category was uniformly set to `4` over all land surfaces when using Noah-MP (see [here](https://github.com/NOAA-GFDL/SHiELD_physics/blob/3027a97d8d828c0ebe1d5ebfbc2b1e44a79c5fdb/gsmphys/sfc_noahmp_drv.f#L74) and [where this variable is used downstream](https://github.com/NOAA-GFDL/SHiELD_physics/blob/3027a97d8d828c0ebe1d5ebfbc2b1e44a79c5fdb/gsmphys/sfc_noahmp_drv.f#L578)).  This category corresponded to a surface with medium reflectivity, producing albedo biases that were most apparent over generally bright desert regions like the Sahara and Arabian Peninsula.  This was already observed in the UFS and they addressed it by prescribing a spatially varying soil color from a climatology and updating the albedo table those categories …
> Port soil color climatology prescription for Noah-MP from UFS to SHiELD

- gsmphys/module_sf_noahmplsm.f90
- gsmphys/noahmp_tables.f90
- gsmphys/sfc_noahmp_drv.f
This PR updates some parameters used in the snow cover fraction scheme of Noah-MP to be consistent with those in official version 4.5.  The commit that added these in the official Noah-MP repository is [here](https://github.com/NCAR/noahmp/commit/03690c5a2df0b6e4352f358f9dab5345c7bb1239).
cc: @kaiyuan-cheng @lharris4
I have tested this in a year-long C24 resolution simulation with prescribed observed 2020 sea surface temperature and sea ice and compared the monthly mean surface albedo to ERA5.  Quantitatively in terms of land RMSE the differences are marginal, but it does seem to help the albedo bias be less systematically negative.
**Checklist:**
> Update parameters used for snow cover fraction scheme

- .github/.parallelworks/checkout.sh
- .github/.parallelworks/compile.sh
- .github/.parallelworks/run_test.sh
- .github/workflows/Intel_Parallelworks_CI.yaml
CI in this repository was not actually testing the code as we only compiled "solo" shield which does not contain a SHiELD_physics component.  In this PR, I have updated the CI to now checkout the code and then compile SHiELD.  Right now I only compile SHiELD nh repro 32bit.  If desired, I can compile other code configurations.   I also plan to add a SHiELD test to the CI very soon, but this PR can go in first.
This is tested on Parallelworks.  When this PR is created, the CI in this branch automatically runs.
**Checklist:**
> Update the CI

- GFS_layer/GFS_radiation_driver.F90
- GFS_layer/GFS_typedefs.F90
The subroutine `compute_column_integrated_moles_of_dry_air_and_co2` is [called](https://github.com/NOAA-GFDL/SHiELD_physics/blob/main/GFS_layer/GFS_radiation_driver.F90#L1389) by default to compute:
`Diag%column_moles_dry_air_per_square_meter` and `Diag%column_moles_co2_per_square_meter` in [GFS_layer/GFS_radiation_driver.F90:](https://github.com/NOAA-GFDL/SHiELD_physics/blob/main/GFS_layer/GFS_radiation_driver.F90#L1946)
These quantities are not allocated in [GFS_layer/GFS_typedefs.F90](https://github.com/NOAA-GFDL/SHiELD_physics/blob/main/GFS_layer/GFS_typedefs.F90#L3923) if ldiag3d is false in gfs_physics_nml.
Thus, this causes a code crash.
This PR will add an if statement before calling compute_column_integrated_moles_of_dry_air_and_co2
Tested within shield in debug …
> fix bug when calling unallocated diagnostics

- FV3GFS/FV3GFS_io.F90
- GFS_layer/GFS_physics_driver.F90
- gsmphys/module_sf_noahmplsm.f90
- gsmphys/sfc_noahmp_drv.f
A number of fixes, updates, and code clean-up related to Noah-MP:
1. fix issue with iems = 2, together with updated surface emissivity initialization. Originally, the surface emissivity was 0.95 everywhere anytime over land and sea-ice. The fix gives realistic spatial and temporal distribution of surface emissivity.
2. fix wrong type of precipitation passed to Noah-MP. Specifically, this PR fixes that falling cloud ice was passed into Noah-MP as falling hail.
3. fix the representation of mixing ratio. Correct conversion from modified specific humidity (vapor_mass/[dry_mass + vapor_mass]; used in the GFS physics) to mixing ratio.
4. fix potential temperature calculation
5. fix water table recharge, based on [version 4.5 of the official Noah-MP …
> Fixes and updates related to Noah-MP

- FV3GFS/FV3GFS_io.F90
- GFS_layer/GFS_physics_driver.F90
- GFS_layer/GFS_radiation_driver.F90
- GFS_layer/GFS_typedefs.F90
This PR adds the ability to output dual radiative flux diagnostics representing what the fluxes would be with up to eight different user-specified scalings of carbon dioxide.  These diagnostics are made optional, since for each provided scale factor an additional call to the radiative transfer code must be made.  The motivation for these diagnostics is to make it possible to quantify the impact of modifying the CO2 concentration for a given atmospheric state.  This flavor of diagnostic is often used to quantify the direct forcing of other constituents like aerosols.
Enabling these diagnostics requires modifying two namelist parameters:
- `gfs_physics_nml.do_diagnostic_radiation_with_scaled_co2` must be set to `.true.`.
- …
> Add optional radiative flux diagnostics with perturbed CO2

- atmos_shared/atmos_global_diag.F90
- atmos_shared/atmos_tracer_driver.F90
Updates real kind of some variables given that their corresponding routines are called from the full coupler which is compiled in 64bit.
> allows mix precision compilation

- FV3GFS/FV3GFS_io.F90
- GFS_layer/GFS_physics_driver.F90
- GFS_layer/GFS_typedefs.F90
1. Update to IFS SST input routine based on the latest restart reading standard
2. Addition of a namelist option: scale_awareness_factor
Tested by Linjiong
**Checklist:**
> Bringing in updates from Gitlab

- FV3GFS/FV3GFS_io.F90
- GFS_layer/GFS_physics_driver.F90
- GFS_layer/GFS_typedefs.F90
#51 introduced the machinery to compute and output radiation diagnostics from SHiELD with scaled CO2 concentration.  However, it only provided diagnostics for the surface and top of atmosphere fluxes.  Having vertically resolved heating rate information can also be valuable.  This PR makes the mostly boilerplate / plumbing updates needed to expose the 3D heating rates computed by the radiation multi-calls as diagnostics in a similar way.
The usage is the same as that described in #51, though one must also specify `gfs_physics_nml.ldiag3d = .true.`.  The multi-call diagnostics exposed have names of the form:
- `gfs_phys/tendency_of_air_temperature_due_to_longwave_heating_with_scaled_co2_1`
- `gfs_phys/tendency_of_air_temperature_due_to_shortwave_heating_with_scaled_co2_1`
- …
> Expose 3D heating rates from radiation multi-calls as diagnostics

- GFS_layer/GFS_physics_driver.F90
- GFS_layer/GFS_typedefs.F90
- gsmphys/sfc_diff_coupled.f
- gsmphys/sfc_ocean_coupled.f
Updates to SHiELD Surface physics subroutines to address inconsistent Land-Sea Masks between SHiELD and MOM6 in real-world applications
The logic behind the updates is as follows:
- For SHiELD "land" points: Always use the SHiELD land model (Noah or Noah MP).
- For SHiELD "sea" points:
- If the corresponding points are also "sea" points in MOM6: Use surface data produced by the Coupler.
- If the corresponding points are not "sea" points in MOM6: Use the surface physics built into SHiELD.
The inconsistent "sea" points in SHiELD and MOM6 can be categorized as follows:
- Lakes: SHiELD masks them as "sea" points, but MOM6 treats them as "land" points.
- Ocean Basins Not of Interest: Regional MOM6 may mask them out.
- Coastal Regions: SHiELD and MOM6 may have slightly inconsistent coastlines …
> Updates for handling inconsistent SHiELD and MOM6 land-sea masks

- gsmphys/radiation_gases.f
Changes the conversion of longitudes from `-pi -- pi` to `0 -- 2pi` so negative values are mapped to values greater than pi.
Fixes # 66
**Checklist:**
> quick fix to longitude conversion in co2 assignment

- GFS_layer/GFS_physics_driver.F90
- GFS_layer/GFS_typedefs.F90
Introduce new variables in the `Coupling` data structure to store surface radiative fluxes adjusted to the physics time step (via the `dcyc2` call).
These adjusted fluxes will be passed to the FMSCoupler exchange grid, instead of the fluxes computed at the longer radiation time step, for coupling with the land and ocean component models.
> Introduce new variables for storing adjusted surface radiative fluxes
